services:
  mysql:
    image: mysql:8.4.0
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d  
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: codecamp
      TZ: Canada/Eastern

volumes:
  mysqldata:
    driver: local
